### PR TITLE
Add URL to project

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by chmp** [comment]
Thanks a lot :)

**Comment by chmp** [comment]
Oh sorry. Can you re-open the PR against the develop branch? Thanks a lot.

**Comment by xhochy** [comment]
Note that you can change the branch against which PRs are made in the Github settings ;)

**Comment by chmp** [comment]
You mean by setting the default branch? But then also the front page will point to the develop branch. And since I'm kinda abusing github as my documentation that would be annoying to users. (That was the old state, where released features and documented features were not in sync.)

**Comment by chmp** [comment]
Good news. GH still counts you as a contributor. So at least credit gets assigned :)

**Pull request merged**
